{{- $chartName := include "locky.name" . -}}
{{- $tracingUrl := include "locky.tracingUrl" . -}}
{{- $metricsUrl := include "locky.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{- if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  TELEMETRY_TRACING_RATIO: {{ .Values.env.tracing.ratio | quote }}
  {{- end }}
  {{- if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{- end }}
  {{- with .Values.dbConfig }}
  DB_HOST: {{ .host }}
  DB_NAME: {{ .database }}
  DB_SCHEMA: {{ .schema }}
  DB_PORT: {{ .port | quote }}
  DB_ENABLE_SSL_AUTH: {{ .sslAuth.enabled | quote }}
  {{- if .sslAuth.enabled }}
  DB_CERT_SECRET_NAME: {{ .sslAuth.secretName }}
  DB_CERT_PATH: /tmp/certs/{{ .sslAuth.certFileName }}
  DB_KEY_PATH: /tmp/certs/{{ .sslAuth.keyFileName }}
  DB_CA_PATH: /tmp/certs/{{ .sslAuth.caFileName }}
  {{- end }}
  {{- end -}}
  {{- with .Values.env.app }}
  APP_RESERVE_LOCK_EXPIRATION: {{ .reserveLockExpiration | quote }}
  {{- end -}}
  {{- with .Values.env.mediator }}
  MEDIATOR_TIMEOUT: {{ .timeout | quote }}
  MEDIATOR_ENABLE_RETRY_STRATEGY: {{ .retryStrategy.enabled | quote }}
  {{- if .retryStrategy.enabled }}
  MEDIATOR_RETRY_STRATEGY_RETRIES: {{ .retryStrategy.retries | quote }}
  MEDIATOR_RETRY_STRATEGY_SHOULD_RESET_TIMEOUT: {{ .retryStrategy.shouldResetTimeout | default false | quote }}
  MEDIATOR_RETRY_STRATEGY_IS_EXPONENTIAL: {{ .retryStrategy.isExponential | default false | quote }}
  MEDIATOR_RETRY_STRATEGY_DELAY: {{ .retryStrategy.delay | quote }}
  {{- end }}
  {{- end -}}
{{- end }}
